version: "3.9"

services:
  web:
    container_name: web
    build: .
    restart: unless-stopped
    ports:
      - 4000:4000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=notesapp
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PORT=4000
      - NODE_ENV=development
    networks:
      - app-network

  postgres:
    container_name: database
    image: postgres:14
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notesapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
