version: "3.9"

services:
  web:
    container_name: web
    build: .
    restart: unless-stopped
    ports:
      - 4000:4000
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/notesdb
      - PORT=4000
      - NODE_ENV=development
    networks:
      - app-network

  mongo:
    container_name: database
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge